- hosts: all
  tasks:
  - name: Getting VMWARE UUID
    vmware_guest_info:
      validate_certs: no
      hostname: 192.168.0.249
      username: administrator@vsphere.local
      password:  P@ssw0rd
      validate_certs: no
      datacenter: datacenter
      name: testvm
      schema: "vsphere"
      properties:
    register: vminfo
  - debug:
      var: vminfo.instance.config.uuid
