- hosts: all
  tasks:
  - name: Getting VMWARE UUID
    vmware_guest_info:
      validate_certs: no
      hostname: 192.168.0.249
      username: administrator@vsphere.local
      password:  P@ssw0rd
      validate_certs: no
      datacenter: datacenter
      name: testvm
      schema: "vsphere"
      properties:
    register: vminfo
    delegate_to: localhost
  - name: Rename virtual machine from old name to new name
    vmware_guest:
      hostname: 192.168.0.249
      username: administrator@vsphere.local
      password:  P@ssw0rd
      validate_certs: False
      cluster: ClusterA
      uuid: vminfo.instance.config.uuid
      name: ttttt
