- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Add disks to virtual machine using UUID
    community.vmware.vmware_guest_disk:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      uuid: 421e4592-c069-924d-ce20-7e7533fab926
      disk:
        - size_mb: 10
          type: thin
          datastore: datacluster0
          state: present
          scsi_controller: 1
          unit_number: 1
          scsi_type: 'paravirtual'
          disk_mode: 'persistent'
        - size_gb: 10
          type: eagerzeroedthick
          state: present
          autoselect_datastore: True
          scsi_controller: 2
          scsi_type: 'buslogic'
          unit_number: 12
          disk_mode: 'independent_persistent'
        - size: 10Gb
          type: eagerzeroedthick
          state: present
          autoselect_datastore: True
          scsi_controller: 2
          scsi_type: 'buslogic'
          unit_number: 1
          disk_mode: 'independent_nonpersistent'
        - filename: "[datastore1] path/to/existing/disk.vmdk"
    delegate_to: localhost
    register: disk_facts
